apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jko-dev
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: jko
    app.kubernetes.io/component: argocd
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JulienKolaric/OpenshiftSNO.git
    targetRevision: main
    path: gitops/namespaces/jko-dev/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: jko-dev
  ignoreDifferences:
    - group: kubevirt.io
      kind: VirtualMachine
      jsonPointers:
        - /status
        - /metadata/finalizers
        - /metadata/annotations
    - group: kubevirt.io
      kind: VirtualMachine
      managedFieldsManagers:
        - virt-controller
        - virt-api
    - group: kubevirt.io
      kind: VirtualMachine
      jqPathExpressions:
        - .spec.template.metadata.annotations
        - .spec.template.spec.architecture
        - .spec.template.spec.domain.firmware
        - .spec.template.spec.domain.machine
        - .spec.template.spec.domain.devices.interfaces[].macAddress
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
