apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - operator-group.yaml
  - subscription.yaml
  - hyperconverged.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: jko
      app.kubernetes.io/component: cnv
